---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ledger-api-secrets
  namespace: payments
spec:
  encryptedData:
    DB_PASSWORD: AgASDBjkRNyLupEUhdal++NBTkPuZ7U9pERA9nU+fNLExyUVNFEwlJnOdkBuBUFGe0e+7qvgkemrOvGgGZXh4bLOvBb1JsoZrFGyVY95of2UM9nI5z+R92DS2bOJkogQJXw7AHqXDQI44TOtx4rHfm7KyP3SqL5qwFMAgtIqMbkBaUDw2N9Vdey35DHQ0kRKKbdj71cG9Fe18ZIRIjJWOG/j6rZJ9GDGktzjtcDN5ChpqYK2rGuoMrwbkosZpbpfsvAgscw2KBSQBeu325tp7088scLgq+7EDP9+wLy6GP5u9va3pS5UFaVOH8aQMpazlZhWGGV2Jlr57P1Kco0iGJJhRzJz9DZyRUKzlwgS8mNa9FYUUSacPsyb2smvtI9SozHfSFzeaUcnactU7SVLCa6GOmnFd1ve5ZI/WemIVuMWQlmT/E0oWxzguCoe4QFp61mfZSxMrE4tN2BbF1rId4NjRKQzu4PHYoMohGMKN6Vv4DY9gtusB6iVXxXkeqPQbMF8dozKyamriRrgCn0bSraJ4id4T6OwSXPilWa3IxSxnPk+Bf1YRmlWd4diQVU8mPLYIoIqZ+R19GgJuSNwkj+8mgw0GMKTm3VQW5X2Y6TA2Gww6GcVQ//gYWc0Cbx4FGmlAV9wKPpC+HK9K7ptZH4FitywY9AiKhoaWclRhsugq2zVkWyXmqgYU7tqMKRBwGA5ELX3Y6RvKZf/mCtXxEZ2rRHVzQ==
    STRIPE_API_KEY: AgAZDPCpdPSZdWfetdHTOjeZYW2f8nO0Lj/50+7nDlpOG9FEyQLXGULKN/7qTK66ICjpLqzm1uzypSZXm4S2JjIz4K19pD7SUU0mlz1zWVWFjT9EtzW96LCFewGubUylfTuSQxhgNSI2nHfJ6I8NpFbkGXqQJDFW06Om3kBrxofILBy9+/lUdzRZVXg3QtSuE+UrAXzKhMStuG1Br2S5XG3y4ugLG49Way+XCA8S9ONE2oKmfQ+8zOf6Jt/gmY9S15l2WsoLjZzwgmMk4It3x1oP/To+J9DipjhNyCX7HeDVUiKisp+3TloRUJ9n6+JwXfV+xy/iLrHskM/gBPnJVDBJSitVPbrlNgB09bHc6nc5EiRQwLgvjQtJb0m7tZ+epBc56p/wswINb1W8DJw9YUtvwzIpHZFFMhsdidPEe6JnN8uIGNTKE4EFuAF6hreQ3K+HtqwqxKGczq9FB0N+iJKK6P1ccC49pbpsG2WsNwRSXyHlT5VkhhM1JM/bwUMYzGl+4nrBGYjNFquLANNFgQ3BIaz3vj8sxWXiZlKTIRXfbTVp8YW+mFosXWcrinozYDByNZRhnUJrt+WwCXRS3Ac6vM34pg4ur41HoggCVBz0OYjMcCV99iwwyymE+YSApX8n6lKbwXasuAe1zz7U7kB1D18waHCGRYhA8gFmkKkl9xz7vXos7NZJThx5SDhwkSQp6DLxKWDd3/3oFOMOfYTH19CyHPpXlAxGtJQhgDoqQ6EH8vPHvfU11Orgz+me
  template:
    metadata:
      creationTimestamp: null
      name: ledger-api-secrets
      namespace: payments
