---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ledger-api-secrets
  namespace: payments
spec:
  encryptedData:
    DB_PASSWORD: AgB3jGzvvw9Nu/BVKTWAwCCe7I/GQ1k69xhI5SHTcNmcgKFOk+aDuoreev4uzklmNwhhY3ArLlIGB5z08t/Ete9IjLbB98nf5DlOXerjJmI/64ePki9OcBC+YiG8JkFgNZBL+xCMxnnAYTJC37Q+zTs+prt+cnMNAUXunG2cFy11MLkxHg6xuxW1mUoE0x2TcZaWa9intCjtLsk8bePwClXrnPVnx/d+fE5ksVmxFCPOtJJLzCigLGz3+uUBpUp3+b/umw1MkAanyEEPQcRNHKnUV/NrZ/FM1yrA3lRjBUEAqK2KOBcnRm1K/kS1mThYHZeXYE1mPFydkeEETSvdXHlnebbesHoqe2CXSBPAtCQVvYGnVQ4KRDd+Ee/jIEzts5KYpvnRzYCPKfbqr2FPMhXtYw1XNYMMLzV+dMoId5ZFWRjgioN+S5ktOjnEm90khm/A/VpWuVhV8/JBLXj+hT88583hEre0zt1IzWdf86ITsHxA68vim2MF1xnkIP7tpxXbz9IOhH6h1hSY4oBpLmtuJkdzGUnvBInKmO8L3Oy4wx3LzQq4TvaKFvvm0H0FZG5nSrduie2kQJjN0r6q2CwPMgNeXieQglIOHZbp/YCJRcTHZ+V7++ZxZcjpEooy/uRdAMiZb2+XuweHwzwvMxg3ZaJPvuop7ELLT2P4bTdki5BwHojY1mpCYDPU+1ixR2ZsLQ+q47UcMiDaXjhXj+FfMbomcQ==
    STRIPE_API_KEY: AgBowlWErVb/Cm7ZnGFMGjMVIBQKxodgIkYpilGFzAqY31+LAq/5snObxW7OONozEOtFUw843AsiTtDEHO82MliwuJA1V0HkjtpijPufH4g4IJQrBXRmjk65erGC13j46a0p960259PsVgx5LSFo1rNM7KPoy0GafEjISCxu1iux8FLeaJ2AIdJ/NiNirRQKZegL0LHEhkpcwW6WhD6J++qz+hMU1d1tbA6x50haO+fr8BJGR0Wx2xGzBjdd+pol5Gdt107BJdnfUhfxoB4hxaS7t4vD4r5wISeMi2XfP4sUrZKrt0TeYnUl7zIbgHUFRTlgH3uvJhlN6fdW4TMK3FOhsjy7VcsDOUCGcBX/IbjpJA67wbLr2H7aigXF97X1wRwp5knlYIt36Qjgu5ny7EvaD4goFsv7ZoUA3N4/jxWfIWvB7kK3wqyrE77B++swHDHKcZplyKTzISoM3C8a02E3RY8x3lnldotEzeWhtLx4hnDp/NrkmJwyOST58JRlDUh+tojOtNDQ4Z7ZLD7BJy6zMVKkQ4qgVV+vIq+aGAHzUXzL3CUdwQDkRLiQnIbwFmZ7MhjuIeb9hwxNvGjSKAv3aUvfOUzoY0wbpYFQhPVYCxJEMO4DDHn1vLg9wZhpE84vxrLDnpgJThzPabzVRTZSj9kMSoyNZS3GiXnivc0+RLblL2FAgnfFDG5+Pyz8Gf6XBzSvGA8Q6HIFsJtdBTVdkovsjCzgoNuQGk9cZku0Sz3gGbjAyQW866wvZJya
  template:
    metadata:
      creationTimestamp: null
      name: ledger-api-secrets
      namespace: payments
