---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ledger-api-secrets
  namespace: payments
spec:
  encryptedData:
    DB_PASSWORD: AgB6XczFqAVZitOoxzc20WDYHIaGOMYjsPmfiP9i1pUi0HRZL0TovxPQG6tv0Jkweryytcbe9KTH7e8UF5wJ9ltwKyDxZzC9Qk9oqF6gAdlMeSkcLIt9Na5JDSmTyX2okvmZueXwCD6+yIIyrdYx1D8XmKmJemh3K83BCFzB+YRxtMaMgd5oqoQLO67sCraakFdcWrqcYIdxqLBZt8VtccDKBr/vFS/9YgJwWofY4zSLlq983xxKqjtWpYjGqKGgi0xSn91+1Pg5GleCqcdRgoP5IndjoOW+SPlYcuz7lodnTp3fXhHnE+KOvAW3Pv35KfNn4L2U14CYZ+8Et1j72FdQNIpwRJbY0rwzUKGdoUN48EETixUhXMswzOjBuDxRprxkTNOJ4bi5Qan5sYlawNOgtilVQ7avdGXKBaEljCIyqM+Kx1Zimc7OJcR/nGrXB8r8r5ZyBIzAiXZZxNcrRVYauZkf484gksMIPz9+lyWyAAe5scdAR6uEuJt5gsZDXPiNGyyAzAc10PMY/b/BW2YnDJwOCARRqLBZX+GS41YUrYnsccCy1TaPbwIVmrv8Eo/DzKmtc0//TqLxJcKpxhHiyUSub+2AHVK+xcZ9hHJqc8scrKERVo4C7GZK9dbvMeAI7Cz0fxSvyavqZgh/xTLO2jGHymI7UGzEwr3LtT4HaLLDKmEvCgaEWF30MJ5yGX8OraZA6PhLX2cib1tPCAO43h5cNA==
    STRIPE_API_KEY: AgBbMp7tI+PaF14zHnW4zhEJiwiVA7S/01MO9CN9Z9oDyh3h2t9fbpJk6PLZFNxzi9T64+BURkxDJ9sGSJooomnBqJpwx3gFch5v5Ms944euAtHUOtaDmrBnIzJccIL/5E+oayerDsEEO5g1UE6AzT1iGRDUSCcK2tMVXJluccX7Lt6RUkwEdKaqpezI1I9zGNYmoJEKwCBftNoQI/IhxWd5TeftsX9UZhDq4+FWsY+c+jRaCzU+0pplvfjQwsFdwVa/09oSdgcWt13MflRDr8rCOSfiw+DbwPfNnwyZISFjhzF5moEou1Orxpm7izh45zwpKqBY4AhIkO+U/+x9SCC2leGkJm2bWxC10bfl4jcr7hr+wh0gOxNgNEGZWk4jath0GkqXALB3R1GZygtIgH+pz6pfMzM/UJe+lN+7/F7ifr7qCwux1ZZKJW4BAdOtxxy6qzuodu32WIZBlcFAodJej5JnUP7b+5wyYxVOy2+ww+zqgvKKPo/UGtcNZklXiW2F3wU7xHb6goneHd/myLIEIh7pb5N8VhdBGS/W6QvlbtL1Emee6keoQbR9x0KE9w5iWyzfWHpwVk9EwCu1Ipj9en+wLkuMzm0rV+bWcSyUP+TN3NHavNfAcmn8QrvsEqj0qNwC9FG0Se8UpoVwwCFkJBW6DrlGiynvUzGnWcDyBdA4kaKNH50hpnJAp2CMN1fhULyEF/qgCQik7+UgvFyjRpHtno2cFtzAELsRcbY/yuZCJSt1iUN1WFVJcdRm
  template:
    metadata:
      creationTimestamp: null
      name: ledger-api-secrets
      namespace: payments
